# Generated by Django 4.2.15 on 2024-10-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_acivated_at_profile_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='acivated_at',
        ),
        migrations.AddField(
            model_name='profile',
            name='activated',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
